name: Squad APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache libncurses5 libffi-dev \
          libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev libpng-dev \
          libgl1-mesa-dev libgles2-mesa-dev python3-pip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aspire-med-app.apk
        path: bin/*.apk
