name: Squad APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk zlib1g-dev libjpeg-dev libpng-dev
          buildozer -v android debug

      - name: List APK Files
        run: find . -name "*.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aspire-med-app-release
          path: .buildozer/android/platform/build/dists/**/bin/*.apk
          
