name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev python3-pip unzip openjdk-11-jdk

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        mv $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: aspire-med-app.apk
        path: bin/*.apk
