name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev python3-pip python3-setuptools python3-wheel
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: aspire-med-app.apk
        path: bin/*.apk
