name: Build APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Squad APK Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aspire-med-app-debug-apk
          path: bin/*.apk
